
- name: Install kubectl
  # https://kubernetes.io/docs/tasks/tools/install-kubectl/
  shell: |
      KUBE_VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
      wget -O /tmp/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl
      chmod +x /tmp/kubectl
      sudo mv /tmp/kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/kubectl

- name: Create .kube directory
  file:
    path: "/home/{{ user }}/.kube"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"   

- name: Create zsh completions directory
  file:
    path: "/home/{{ user }}/.oh-my-zsh/completions"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
    recurse: yes

- name: Set kubectl auto-completion
  shell: |
      kubectl completion zsh > "/home/{{ user }}/.oh-my-zsh/completions/_kubectl"
  args:
    creates: /home/{{ user }}/.oh-my-zsh/completions/_kubectl

- name: Create a symbolic link to Windows kube config
  file:
    src: "{{ user_windows_path }}/.kube/config"
    dest: "/home/{{ user }}/.kube/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link

- name: Install Helm
  # https://helm.sh/docs/intro/install/
  shell: |
      cd /tmp
      wget https://get.helm.sh/helm-v3.3.0-linux-amd64.tar.gz
      tar -zxvf helm-v3.3.0-linux-amd64.tar.gz
      mv linux-amd64/helm /usr/local/bin/helm
      helm repo add stable https://kubernetes-charts.storage.googleapis.com/
  args:
    creates: /usr/local/bin/helm

- name: Set helm auto-completion
  shell: |
      helm completion zsh > "/home/{{ user }}/.oh-my-zsh/completions/_helm"
  args:
    creates: /home/{{ user }}/.oh-my-zsh/completions/_helm

- name: Create kubectx completions foler
  file:
    path: /opt/kubectx/completion
    state: directory


- name: Install kubectx and kubens
  shell: |
      curl -O https://raw.githubusercontent.com/ahmetb/kubectx/master/kubectx
      chmod +x kubectx
      mv kubectx /usr/local/bin/
      curl -O https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens
      chmod +x kubens
      mv kubens /usr/local/bin/
      BASE_URL=https://raw.githubusercontent.com/ahmetb/kubectx/master/completion
      curl -O ${BASE_URL}/kubectx.zsh
      curl -O ${BASE_URL}/kubens.zsh
      mv kubectx.zsh /opt/kubectx/completion
      mv kubens.zsh /opt/kubectx/completion
      ln -s /opt/kubectx/completion/kubectx.zsh /home/{{ user }}/.oh-my-zsh/completions/_kubectx.zsh
      ln -s /opt/kubectx/completion/kubens.zsh /home/{{ user }}/.oh-my-zsh/completions/_kubens.zsh
  args:
    creates: /usr/local/bin/kubectx
  
- name: Install K9s
  unarchive:
    src: https://github.com/derailed/k9s/releases/download/v0.19.6/k9s_Linux_x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: True

- name: Download Octant
  get_url: 
    url: https://github.com/vmware-tanzu/octant/releases/download/v0.12.1/octant_0.12.1_Linux-64bit.deb
    dest: /tmp/octant.deb

- name: Install Octant
  apt:
    deb: /tmp/octant.deb


- name: Install Linkerd
  shell: |
      curl -sL https://run.linkerd.io/install | sh
  args:    
    creates: "/home/{{ user }}/.linkerd2/bin"


