- name: pip self-update
  pip:
    name: pip
    state: latest
    executable: pip3

- name: Install Python Packages
  pip:
    name:
      - pipenv
      - docker-compose
      - selenium
    executable: pip3

# Only works if Browser is installed.  Functionality currently broken in WSL
# - name: Install Firefox Geckodriver for Selenium
#   unarchive:
#     src: https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
#     dest: /usr/local/bin
#     remote_src: True

# - name: Install Chromedriver for Selenium
#   unarchive:
#     src: https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
#     dest: /usr/local/bin
#     remote_src: True
