   
- name: Install Oh-My-Zsh
  shell: |
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh/

- name: Set Oh-My-Zsh owner
  file:
    path: ~/.oh-my-zsh
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes

- name: Create antigen directory
  file:
    path: ~/.antigen
    state: directory

- name: Install Antigen
  shell: curl -L git.io/antigen > ~/.antigen/antigen.zsh
  args:
    creates: ~/.antigen/antigen.zsh

- name: Set permissions on antigen directory
  file:
    path: ~/.antigen
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes
    mode: '0755'

- name: Copy zshrc
  copy:
    dest: ~/.zshrc
    src: ./.zshrc
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Copy .p10k.zsh
  copy:
    dest: ~/.p10k.zsh
    src: ./.p10k.zsh
    owner: "{{ user }}"
    group: "{{ user }}"
        